# Generated by Django 2.1.15 on 2020-11-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=30)),
                ('prenom', models.CharField(default='', max_length=50)),
                ('dateN', models.DateField(default='')),
                ('adresse', models.CharField(default='', max_length=70)),
                ('contact', models.CharField(default='', max_length=20)),
                ('fonction', models.CharField(default='', max_length=15)),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2020-11-27')),
                ('due_date', models.DateField(default='2020-11-27')),
                ('category', models.ForeignKey(default='general', on_delete='restrict', to='app.Category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
